version: "3.9"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: transformix-backend
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - UVICORN_PORT=8000
      - UVICORN_HOST=0.0.0.0
    volumes:
      - backend_data:/data
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: transformix-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  backend_data: {} 